### ISSUE TITLE
CPU Load experiment for Windows environment 

### ISSUE THREAD

**Issue by takhtar3** [chaosblade-io/chaosblade-exec-os#108]
## Issue Description

We are trying to replicate the logic used to create the CPU load for Windows machine. 

Can any one please shed some light about the logic used to create the CPU load. 
 
We are going through this code 

https://github.com/chaosblade-io/chaosblade-exec-os/blob/master/exec/cpu.go

Can some one please highlight what part of the code is creating the load for CPU ?

### Tell us your environment

Windows VM 
CPU : 4 Core

**Comment by MandssS** [comment]
There is currently no support plan for the community edition, but our enterprise edition does.

enterprise: https://ahas.console.aliyun.com/
