### ISSUE TITLE
burncpu question

### ISSUE THREAD

**Issue by sanxun0325** [chaosblade-io/chaosblade-exec-os#111]
## Issue Description

Type: *QA*

### Describe what happened (or what feature you want)
runtime.Gosched() 是必要的嘛？在runtime.Gosched()前已经执行了time.sleep()这已经可以让出cpu时间片了
https://github.com/chaosblade-io/chaosblade-exec-os/blob/master/exec/bin/burncpu/burncpu.go#L164

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by tiny-x** [comment]
我理解也是没有必要，我在 1.6.0-dev 分支上换了下位置，并且去除了获取当前进程的 CPU 的逻辑，因为在核心非常多的情况下，目前的算法是不能打满 CPU 的。
