### ISSUE TITLE
Fix disk-fill cannot control the disk load accurately

### ISSUE THREAD

**Issue by sunyujie666** [chaosblade-io/chaosblade-exec-os#64]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
I found that Disk-Fill could not control disk load accurately.
![image](https://user-images.githubusercontent.com/43567097/97144264-17b66380-179f-11eb-9432-44c4067347a3.png)

### Describe what you expected to happen
If I set the parameter to a number, then the disk load should be that number。

### How to reproduce it (as minimally and precisely as possible)

1. a large disk(more than 100G) 
2. use percent :less than 1%
3. do the disk-fill experiment

### Tell us your environment
linux

### Anything else we need to know?
Can you improve the accuracy in the function calculateFileSize？
I have set the accuracy to .6f from 0.2f  and compile it.
It works!
![image](https://user-images.githubusercontent.com/43567097/97145723-a2985d80-17a1-11eb-8d73-60c22df40b77.png)
![image](https://user-images.githubusercontent.com/43567097/97145848-d3789280-17a1-11eb-8731-731ff8c17115.png)

thanks

**Comment by tiny-x** [comment]
Welcome to summit a PR to fix it.

**Comment by donngchao** [comment]
Maybe it has something to do with the machine‘s behavior, my test machine did not reproduce this phenomenon.
(CentOS Linux release 7.2 (Final))
