### ISSUE TITLE
内存注入，内存使用率(90-95)和内存占用速率设置很大运行命令直接OOM退出报错

### ISSUE THREAD

**Issue by caizhichao666** [chaosblade-io/chaosblade-exec-os#79]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
内存占用率90-95或者内存使用速率也很大。执行命令直接报错或者内存占用率上升一点点后就报OOM溢出程序直接退出
实际上我的可用内存还有很多
![OOM](https://user-images.githubusercontent.com/61259283/110676224-b1daed80-820e-11eb-8aff-aabc4ea577b1.jpg)

  报错 笔记

### Describe what you expected to happen
为了快速实现内存90%-95%情况，往往会将占用速率设置很大等于或大于2048，但执行时会出错，程序会退出

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
CentOS-7-x86_ 64-dvd-1908 

### Anything else we need to know?

执行期间并未有其它很占内存的服务，效果可能是执行前内存使用率13%,我想达到95%，将占用速率和占用率设置都很高，观察top内存使用情况发现也许我只达到20%执行就会OOM退出。如果我将速率下调一些就会正常。请问有什么办法规避这个OOM吗

**Comment by buhuipao** [comment]
我提交的这个：https://github.com/chaosblade-io/chaosblade-exec-os/pull/89 可能可以缓解这个

**Comment by xcaspar** [comment]
> 我提交的这个：#89 可能可以缓解这个

@caizhichao666 It has been released in v1.3.0 version.
