### ISSUE TITLE
Blade is not compiling.

### ISSUE THREAD

**Issue by BPJ94487** [chaosblade-io/chaosblade-exec-os#91]
### Describe what happened (or what feature you want):

-Blade will not compile. 

### Describe what you expected to happen

-I expect Blade to compile without error.

### How to reproduce it (as minimally and precisely as possible)
1. compile with the command "make build_with cli is" 
2. Will receive the following error:
github.com/chaosblade-io/chaosblade-exec-os/exec
exec/systemd_stop.go:114:60: undefined: spec.CommandSystemctlNotFound
exec/systemd_stop.go:115:27: too many arguments in call to spec.ResponseFail
exec/systemd_stop.go:115:28: undefined: spec.CommandSystemctlNotFound
exec/systemd_stop.go:115:76: undefined: spec.SystemdNotFound
exec/systemd_stop.go:116:21: undefined: spec.SystemdNotFound
exec/systemd_stop.go:120:72: undefined: spec.SystemdNotFound
exec/systemd_stop.go:121:27: too many arguments in call to spec.ResponseFail
exec/systemd_stop.go:121:28: undefined: spec.SystemdNotFound
exec/systemd_stop.go:122:33: undefined: spec.SystemdNotFound
 
### Tell us your environment

-Linux

**Comment by kelvinguo0210** [comment]
Me too.  
However I the v1.2.0 is ok. @BPJ94487  hope it's helpful for you to make forward temporarily.

**Comment by xcaspar** [comment]
Please use the latest master branch or the latest released version tag branch to compile.
